name: BuildMingw

on:
  workflow_dispatch

jobs:
  windows-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake (MinGW)
        run: cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -- -j4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myApp-windows-mingw
          path: build/myApp.exe