name: Build

on:
  workflow_dispatch

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build -S . -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myApp-windows
          path: |
            build/Release/myApp.exe
          compression-level: 9
  

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myApp-macos
          path: |
            build/myApp
          compression-level: 9
          if-no-files-found: warn
